// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALYltbEHg1QAecgM-FqtWXkYnq3BWXWgE',
    appId: '1:827027670946:web:4d6dd77e61af63853b14fb',
    messagingSenderId: '827027670946',
    projectId: 'jewellery-604f7',
    authDomain: 'jewellery-604f7.firebaseapp.com',
    databaseURL: 'https://jewellery-604f7-default-rtdb.firebaseio.com',
    storageBucket: 'jewellery-604f7.appspot.com',
    measurementId: 'G-QENVQTDM1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqRkOA0ZoBX5ZkMmgMbx8JSyTiakQVPQU',
    appId: '1:827027670946:android:b9e81d1d56b031653b14fb',
    messagingSenderId: '827027670946',
    projectId: 'jewellery-604f7',
    databaseURL: 'https://jewellery-604f7-default-rtdb.firebaseio.com',
    storageBucket: 'jewellery-604f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCShvbe4aqigXlq5Mgx0sziFqC_ICuThc',
    appId: '1:827027670946:ios:d7b5fd1f55b3506e3b14fb',
    messagingSenderId: '827027670946',
    projectId: 'jewellery-604f7',
    databaseURL: 'https://jewellery-604f7-default-rtdb.firebaseio.com',
    storageBucket: 'jewellery-604f7.appspot.com',
    iosClientId: '827027670946-ri8kesn92r02jh47ti6bje7b5rc11b57.apps.googleusercontent.com',
    iosBundleId: 'com.example.jewelleryApp',
  );
}
